-- DROP TABLE IF EXISTS walls CASCADE;

-- CREATE TABLE walls (
--   id SERIAL PRIMARY KEY NOT NULL,
--   user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
--   resource_id INTEGER REFERENCES resources(id) ON DELETE CASCADE,
-- );
